#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BackL,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

task drive()
{
		int x;
		int y;
		int rot;
		int deadzone = 10;
	while(true)
	{
		getJoystickSettings(joystick);


		if (abs(joystick.joy1_x2) > deadzone) {rot = joystick.joy1_x2;} else {rot = 0;}
		if (abs(joystick.joy1_x1) > deadzone) {x = joystick.joy1_x1;} else {x = 0;}
		if (abs(joystick.joy1_y1) > deadzone) {y = joystick.joy1_y1;} else {y = 0;}

		motor[FrontL] = y - rot + x;
		motor[BackL] = y - rot - x;
		motor[FrontR] = -y - rot + x;
		motor[BackR] = y + rot + x;

		wait1Msec(5);
	}
}

//Please comment unfinished code, prevents compiling otherwise
/*task rampnipulator()
{

	while(true)
	{
		getJoystickSettings(joystick);
*/

task main()
{
	waitForStart();
	startTask(drive);
	while(true)
	{
		wait1Msec(5);
	}
}
