#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     SENSOR_GYRO,    sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorLR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorLL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorM,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorKek,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sBasketR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    sBasketL,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTubeGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libsModified_14.h";
#include "JoystickDriver.c";
#include "6210_autonomous_functions.h";

/* Auto60R.c
* Ramp autonomous bringing 60cm to parking zone and scoring
* Created by by 6210 Stryke
* 2014-2015 */

task main()
{
	waitForStart();
	moveTo(-15, -900, 0.8);
	stopMotors();
	wait1Msec(50);
	bFloatDuringInactiveMotorPWM = true;
	moveTo(0, -3100, 0.8, 3000);
	bFloatDuringInactiveMotorPWM = false;
	openGrabber();
	moveTo(-20, -2000, 0.8);//Move back to 60cm rolling goal
	wait1Msec(500);
	closeGrabber(); //Close grabber on 60cm rolling goal
	liftControl(1); //Raise lift to 60cm
	wait1Msec(2400); //Time it takes for the lift to raise to proper height
	liftControl(2); //Stop lift
	setBasket(3); //Tilt basket to dump balls into 60cm rolling goal
	wait1Msec(1500);
	setBasket(1); //Return basket to upright position
	wait1Msec(200);
	turn(25, 30); //Turn 30 degrees (cw) to parking zone
	moveTo(40, 9000, 0.8); //Move to parking zone
	turn(40, -180); //Turn 180 degrees (ccw) to put 60cm rolling goal into parking zone
	stopMotors();
	wait1Msec(100);
}
