#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     SENSOR_GYRO,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SENSOR_IR,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorLR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorLL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorM,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorKek,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sBasketR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    sBasketL,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTubeGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "libsModified_14.h";
#include "6210_autonomous_functions.h";

task main()
{
	arcTurn (-20, -2);
	moveTo (-70, -3500, 0.8);
	openGrabber();
	moveTo (-30, -3000, 0.8);
	setBasket(1);
	wait1Msec(100);
	closeGrabber();
	liftControl(1);
	wait1Msec(2600);
	liftControl(2);
	setBasket(3);
	wait1Msec(200);
	arcTurn (-60, -30);
	setBasket(1);
	moveTo(80, 4000, 0.8);
	turn (-100, 178);
	wait1Msec(100);
	openGrabber();
	/*
	moveTo (-60, -1, 0.8);
	openGrabber();
	liftControl(3);
	wait1Msec(2600);
	liftControl(2);
	treadControl(1);
	moveTo (60, 1, 0.8);
	turn (60, 180);
	openGrabber();
	moveTo (-50, -1, 0.8);
	closeGrabber();
	liftControl(1);
	wait1Msec(2300);
	liftControl(2);
	setBasket(3);
	moveTo (100, 1, 0.8);
	turn (50, 160);*/
}
