#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     SENSOR_GYRO,    sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorLR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorLL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorM,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorKek,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sBasketR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    sBasketL,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTubeGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libsModified_14.h";
#include "JoystickDriver.c";
#include "6210_autonomous_functions.h";

/* Auto30PZ.c
* Parking zone autonomous bringing 30cm to parking zone and scoring
* Created by by 6210 Stryke
* 2014-2015 */

task main()
{
	waitForStart();
	moveTo(-40, -500, 0.8);//move back to give room for turn
	turn(33, 30);//turn 30 degrees (cw)
	moveTo(-40, -2800, 0.8);//move back a little more, around center goal
	turn(33, -29);//turn -27 "degrees", 30 is over (ccw)
	openGrabber(); //open grabber
	moveTo(-40, -4800, 0.8);//move back to 30cm tube
	closeGrabber();//grab 30cm tube
	moveTo(40, 2000, 0.8);//move forward to wall between ramp and parking zone
	turn(-30, 156);//turn 156 degrees (ccw)
	moveTo(-40, -4300, 0.8);//move backwardsto fully place 30cm tube in parking zone
	setBasket(1);//tilt basket
	motor[motorLL] = 85;//raise lift
	motor[motorLR] = 85;
	wait1Msec(1500);
	motor[motorLL] = 0;//stop lift
	motor[motorLR] = 0;
	setBasket(3);//tilt basket back
	wait1Msec(1500);
}
